// 렌더러에 노출하는 유일한 통로. Node 는 열지 않는다 (contextIsolation: true).
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('orc', {
  tasks: () => ipcRenderer.invoke('tasks'),
  projects: () => ipcRenderer.invoke('projects'),
  pickProject: () => ipcRenderer.invoke('project-pick'),
  useProject: (dir) => ipcRenderer.invoke('project-use', dir),
  worktrees: () => ipcRenderer.invoke('worktrees'),
  createWorktree: (payload) => ipcRenderer.invoke('worktree-create', payload),
  removeWorktree: (dir) => ipcRenderer.invoke('worktree-remove', dir),
  sessions: () => ipcRenderer.invoke('sessions'),
  reviews: () => ipcRenderer.invoke('reviews'),
  dashboard: () => ipcRenderer.invoke('dashboard'),
  debug: () => ipcRenderer.invoke('debug'),
  crashTest: () => ipcRenderer.invoke('crash-test'),
  convList: () => ipcRenderer.invoke('conv-list'),
  convStart: (kind) => ipcRenderer.invoke('conv-start', kind),
  convOpen: (payload) => ipcRenderer.invoke('conv-open', payload),
  convView: () => ipcRenderer.invoke('conv-view'),
  convSend: (text, write) => ipcRenderer.invoke('conv-send', text, write),
  convMode: (mode) => ipcRenderer.invoke('conv-mode', mode),
  convOrchestrator: (choice) => ipcRenderer.invoke('conv-orchestrator', choice),
  convSteps: () => ipcRenderer.invoke('conv-steps'),
  orchestrators: () => ipcRenderer.invoke('orchestrators'),
  convPlanAs: (taskId) => ipcRenderer.invoke('conv-plan-as', taskId),
  convReplan: (taskId) => ipcRenderer.invoke('conv-replan', taskId),
  convRead: () => ipcRenderer.invoke('conv-read'),
  convApprove: (payload) => ipcRenderer.invoke('conv-approve', payload),
  convCancel: () => ipcRenderer.invoke('conv-cancel'),
  convEscalate: () => ipcRenderer.invoke('conv-escalate'),
  convReject: () => ipcRenderer.invoke('conv-reject'),
  convAsk: () => ipcRenderer.invoke('conv-ask'),
  convGitInit: () => ipcRenderer.invoke('conv-git-init'),
  convRun: (terminal) => ipcRenderer.invoke('conv-run', terminal),
  convTerminal: (terminal) => ipcRenderer.invoke('conv-terminal', terminal),
  convRename: (name) => ipcRenderer.invoke('conv-rename', name),
  convRole: (role) => ipcRenderer.invoke('conv-role', role),
  convClose: () => ipcRenderer.invoke('conv-close'),
  convEnd: (ref) => ipcRenderer.invoke('conv-end', ref),
  convReopen: (ref) => ipcRenderer.invoke('conv-reopen', ref),
  convArchive: (ref, on) => ipcRenderer.invoke('conv-archive', ref, on),
});
